### ISSUE TITLE
NEB cannot optimize by RFO

### ISSUE THREAD

**Issue by littlemoonstones** [eljost/pysisyphus#163]
Hi,
I tried the different optimizers(L-BFGS, RFO, FIRE) for NEB, but **RFO cannot be used in NEB**. And here is the error message:
```txt
pysisyphus/optimizers/HessianOptimizer.py", line 436, in housekeeping
	if self.geometry.internal:
AttributeError: 'NEB' object has no attribute 'internal'
```
This is my configure file:
```yaml
preopt:
 max_cycles: 10
interpol:
 type: linear
 between: 6
cos:
 type: neb
opt:
 type: rfo
 max_cycles: 15
calc:
 type: xtb
 charge: 0
 mult: 1
 pal: 4
geom:
 type: cart
 fn: [test_data.trj]

```
 And this is my testing data:
[data.zip](https://github.com/eljost/pysisyphus/files/7438736/data.zip)

Thanks
