### ISSUE TITLE
Advice concerning coordinate exceptions in COS calculations

### ISSUE THREAD

**Issue by RaphaelRobidas** [eljost/pysisyphus#218]
When running Growing String calculations with `dlc` coordinates, I sometimes get the following error:
```python
traceback (most recent call last):
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/intcoords/helpers.py", line 36, in get_tangent
    tangent = prims2 - prims1
valueerror: operands could not be broadcast together with shapes (512,) (256,) 

during handling of the above exception, another exception occurred:

traceback (most recent call last):
  file "/home/robidasr/env/bin/pysis", line 8, in <module>
    sys.exit(run())
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/run.py", line 2022, in run
    run_result = run_from_dict(run_dict, **run_kwargs)
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/run.py", line 1966, in run_from_dict
    run_result = main(run_dict, restart, cwd, scheduler)
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/run.py", line 1489, in main
    opt_result = run_opt(
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/drivers/opt.py", line 143, in run_opt
    opt.run()
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/optimizers/optimizer.py", line 725, in run
    step = self.optimize()
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/optimizers/stringoptimizer.py", line 82, in optimize
    forces = self.geometry.forces
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/cos/growingstring.py", line 388, in forces
    perp_forces = np.array([self.get_perpendicular_forces(i) for i in indices])
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/cos/growingstring.py", line 388, in <listcomp>
    perp_forces = np.array([self.get_perpendicular_forces(i) for i in indices])
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/cos/chainofstates.py", line 329, in get_perpendicular_forces
    tangent = self.get_tangent(i)
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/cos/growingstring.py", line 373, in get_tangent
    tangent = self.images[next_ind] - self.images[i]
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/geometry.py", line 328, in __sub__
    diff = -get_tangent(
  file "/home/robidasr/env/lib/python3.9/site-packages/pysisyphus/intcoords/helpers.py", line 38, in get_tangent
    raise differentprimitivesexception
pysisyphus.intcoords.exceptions.differentprimitivesexception
```

Is there a way to either solve this issue or make pysisyphus try again with different primitives? The calculation could use Cartesian coordinates instead, but of course `dlc` coordinates are preferable, even if it takes Pysisyphus a couple attempts to get them right.

**Comment by eljost** [comment]
Dear Raphael,

which version are you using?
Can you make your input available? If so, I can take a look at it.

All the best
Johannes

**Comment by RaphaelRobidas** [comment]
Dear Johannes,

I have retrieved a couple cases where this happens. They occurred with version 0.7.6.post2.
The input is always this:
```
geom:
 type: dlc
 fn: [gsm_start.xyz, gsm_end.xyz]
calc:
 type: orca
 pal: 4
 charge: 1
 mult: 1
 keywords: B97-D3 CPCM(CH2Cl2) defgrid1
preopt:
  max_cycles: 12
cos:
 type: gs
 max_nodes: 13
 climb: true
 fix_ends: true
opt:
 type: string
 stop_in_when_full: 10
 align: false
tsopt:
 type: rsprfo
 max_cycles: 25
 trust_max: 0.2
 thresh: gau
 hessian_recalc: 14
 hessian_init: calc
 do_hess: True
```

[Here are the start and end geometries for three cases.](https://github.com/eljost/pysisyphus/files/9359409/gsm_inputs.zip) The error occurs after a couple cycles of string growth.

Thanks very much!
