### ISSUE TITLE
RICC2 hessian

### ISSUE THREAD

**Issue by AdityaNPanda** [eljost/pysisyphus#220]
Is there a plan to implement ricc2/escf hessian in the near future?

**Comment by eljost** [comment]
I made a commit on the dev-branch that fixes some issues and attached you can find an example:
[ricc2_irc_example.zip](https://github.com/eljost/pysisyphus/files/9535881/ricc2_irc_example.zip)

Please also see the YAML input below, which should be more or less equivalent to the python script in the zip file.
```yaml
geom:
 type: cart
 fn: ethene.xyz
calc:
 type: turbomole
 control_path: /home/johannes/tmp/334_ricc2_irc/control_path
 track: True
 pal: 6
irc:
 type: eulerpc
 downhill: True
 # hessian_init can be one of the options in 
 #   pysisyphus/optimizers/guess_hessians.py:get_guess_hessian() 
 # but not 'calc', as this is not implemented for ricc2 ;).
 hessian_init: fischer
```
