### ISSUE TITLE
ORCA Singlet-to-Triplet TDDFT ES_OPT AssertionError

### ISSUE THREAD

**Issue by fredauski** [eljost/pysisyphus#226]
Hi !
I am greatly enjoying pysisypus so far, it has been immensely helpful to me already!

However I am looking for help with a problem I encountered:
When trying to perform an excited state geometry optimization (singlet-to-triplet) with ORCA 5.0.2/TD-DFT, the calculation encounters an AssertionError (`.err`):

```
   [...]
   File "/pysisyphus/pysis-env-python-3_8_0/lib/python3.8/site-packages/pysisyphus/calculators/ORCA.py", line 707, in prepare_overlap_data
     all_energies = self.parse_all_energies()
   File "/pysisyphus/pysis-env-python-3_8_0/lib/python3.8/site-packages/pysisyphus/calculators/ORCA.py", line 641, in parse_all_energies
     assert len(exc_ens) == len(set(states))
 AssertionError
```

Here is the `RUN.yaml` file:

```
assert: null
barrier: null
calc:
  blocks: '%TDDFT nroots 30 iroot 07 irootmult triplet end'
  charge: 0
  keywords: CAM-B3LYP D4 def2-SVP CPCM(acetonitrile)
  mem: 3800
  mult: 1
  ovlp_type: tden
  pal: 8
  track: true
  type: orca
cos: null
endopt: null
geom:
  coord_kwargs: {}
  fn: geometry.xyz
  type: redund
glob: null
interpol: null
irc: null
md: null
mdp: null
opt:
  T: 298.15
  do_hess: false
  dump: true
  max_cycles: 150
  overachieve_factor: 2
  p: 101325
  thresh: gau
  type: rfo
perf: null
precontr: null
preopt: null
scan: null
shake: null
stocastic: null
tsopt: null
version: 0.7.6.post2
```

Could this be because ORCA computes both singlet and triplet excited states?  
I.e. ORCA computes 30 singlet and 30 triplet roots here (= 60 excited states), which might be different for other QC software that would only compute the 30 triplet roots.

Example from the qm_calcs output file:

```
-----------------------------------------------------------------------------
         ABSORPTION SPECTRUM VIA TRANSITION ELECTRIC DIPOLE MOMENTS
-----------------------------------------------------------------------------
State   Energy    Wavelength  fosc         T2        TX        TY        TZ
        (cm-1)      (nm)                 (au**2)    (au)      (au)      (au)
-----------------------------------------------------------------------------
   1   19412.4    515.1   0.000003388   0.00006  -0.00615  -0.00443   0.00001
   2   19424.7    514.8   0.000869895   0.01474   0.04686   0.05801   0.09582
   3   22304.6    448.3   0.000434073   0.00641   0.03882   0.03038   0.06306
 [...]
  27   52899.8    189.0   0.005889403   0.03665   0.09829   0.11154   0.12062
  28   53207.6    187.9   0.001439164   0.00890   0.08144   0.04405   0.01824
  29   53348.2    187.4   0.003776049   0.02330  -0.10254  -0.01218  -0.11243
  30   54347.7    184.0   0.004895966   0.02966   0.10699   0.01590   0.13401
  31   14472.6    691.0   spin forbidden (mult=3)
  32   14522.3    688.6   spin forbidden (mult=3)
  33   15155.3    659.8   spin forbidden (mult=3)
 [...]
  58   51209.3    195.3   spin forbidden (mult=3)
  59   51537.8    194.0   spin forbidden (mult=3)
  60   51904.1    192.7   spin forbidden (mult=3)
```

Any help would be greatly appreciated!
