### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cluster' 

### ISSUE THREAD

**Issue by manuelperezesc** [eljost/pysisyphus#287]
I was trying to run a NEB calculation ussing G16 as external quantum chemistry package within a YAML file. My input file was:

geom:
 type: cartesian
 fn: [opt_but.xyz,opt_planar.xyz]
calc:
 type: g16
 mem: 16gb
 keywords: "bmk 6-31g(d,p) TDA=(Root=1,Nstates=10,Singlets) SCRF(PCM,Solvent=toluene)"
 charge: 0
 mult: 1
 pal: 12
cos:
 type: neb
 cluster=True
 cluster_kwargs:
  n_workers: 1
  threads_per_worker: 12
  resources:
   CPU: 12
opt:
 type: lbfgs
 align: True
 max_cycles: 100

**To Reproduce**
Steps to reproduce the behavior.

But then the following error rises: 
TypeError: __init__() got an unexpected keyword argument 'cluster' 

I have tried to remove the "cluster", "cluster_kwargs", "n_workers", "threads_per_worker" sections of the input but then, in any case, I still face an error related to a missing argument:

TypeError: __init__() missing 1 required positional argument: 'route'. Unfortunately, I have not yet found an example of Psisyphus with G16, so I might be doing many things wrongly. 

I downloaded Pysisyphus through Anaconda and I updated my .pysisyphusrc file as:

# Excited state calculators

[gaussian16]
# Cmds to execute. Please ensure that the binaries are found in your $PATH.
cmd=/soft/g16.a03/g16/
formchk=formchk
unfchk=unfchk
rwfdump=rwfdump

**Comment by eljost** [comment]
Dear Manuel,

there  seem to be multiple issues with your YAML file. Please see the commented version below:
```yaml
geom:
 type: cartesian
 fn: [opt_but.xyz,opt_planar.xyz]
calc:
 type: g16
 # Please give just a number; this will then use 16 GB per core
 # mem: 16
 mem: 16gb
 # You don't need quotes here
 route: "bmk 6-31g(d,p) TDA=(Root=1,Nstates=10,Singlets) SCRF(PCM,Solvent=toluene)"
 charge: 0
 mult: 1
 pal: 12
# For a NEB you need an initial/interpolated path
interpol:
 type: redund
 between: 12
cos:
 type: neb
 # Use a colon ':' here, not an '=' sign
 cluster=True
 # cluter_kwargs can be left out normally, as pysisyphus will default to
 # use all CPUs on a given node.
 cluster_kwargs:
  n_workers: 1
  threads_per_worker: 12
  resources:
   CPU: 12
opt:
 type: lbfgs
 align: True
 max_cycles: 100
```

Can you please try to run the YAML file below with your input? You can also modify the calculator type to your Gaussian setup, if XTB is not available.

```yaml
geom:
 type: cartesian
 fn: |
  12
  XYZ file generated by Avogadro.
  C     -3.14976    0.54579    0.03819
  C     -1.84313    0.87601    0.06379
  H     -0.06223    0.07362    0.93571
  H     -0.94509   -1.13815   -0.03886
  H     -0.04970    0.17082   -0.86427
  H     -4.35551   -0.92005   -0.94839
  H     -2.97893   -1.65247   -0.07308
  H     -4.36857   -1.01220    0.85185
  C     -3.72667   -0.84244   -0.03735
  C     -0.67374   -0.07076    0.02101
  H     -1.59825    1.93282    0.12082
  H     -3.86911    1.35888    0.07605
  12
  XYZ file generated by Avogadro.
  C     -3.14217    0.55402   -0.17726
  C     -1.82182    0.78673   -0.13212
  H     -0.56243    2.12575   -1.22692
  H     -2.04496    2.90737   -0.55827
  H     -0.68489    2.46862    0.54339
  H     -4.28092   -1.12692   -0.85225
  H     -2.91905   -1.56716    0.24653
  H     -4.40010   -0.78569    0.91860
  C     -3.71236   -0.81478    0.04820
  C     -1.25173    2.15543   -0.35773
  H     -1.13081   -0.02628    0.07227
  H     -3.83325    1.36704   -0.38131
calc:
 type: xtb
 charge: 0
 mult: 1
 pal: 6
interpol:
 type: redund
 between: 4
cos:
 type: neb
 cluster: True
opt:
 type: lbfgs
 align: True
 max_cycles: 1
```

If this file runs then the issue is just in your YAML input.
